-- -- base de datos de prueba ---

CREATE TABLE IF NOT EXISTS usuarios(
	usuarioId int(11) PRIMARY KEY AUTO_INCREMENT,
  	username varchar(100) NOT NULL,
 	password varchar(10) NOT NULL
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;

INSERT INTO usuarios(username,password) VALUES('usuario','inseguro');

--

/***############################### 
ESTE ES EL QUESIRVE PARA USUARIOS
###################################*/


DROP TABLE IF EXISTS usuarios;
CREATE TABLE IF NOT EXISTS  usuarios (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NULL,
  `password` VARCHAR(45) NOT NULL,
  `estado` INT DEFAULT 0,
  PRIMARY KEY (`id_usuario`));

INSERT INTO usuarios(email,password) VALUES("mail","inseguro");

/*########################################*/



-- MySQL Script generated by MySQL Workbench
-- 01/25/17 12:30:09
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`usuarios` ;

CREATE TABLE IF NOT EXISTS `mydb`.`usuarios` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NULL,
  `password` VARCHAR(45) NOT NULL,
  `estado` INT NULL,
  PRIMARY KEY (`id_usuario`));


-- -----------------------------------------------------
-- Table `mydb`.`proovedores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`proovedores` ;

CREATE TABLE IF NOT EXISTS `mydb`.`proovedores` (
  `id_proveedor` INT NOT NULL AUTO_INCREMENT,
  `razon_social` VARCHAR(250) NOT NULL,
  `referencia` VARCHAR(45) NULL,
  `cuenta` VARCHAR(45) NULL,
  `banco` VARCHAR(45) NULL,
  `sucursal` VARCHAR(45) NULL,
  `plaza` VARCHAR(45) NULL,
  `rfc` VARCHAR(12) NULL,
  `telefono` VARCHAR(20) NULL,
  `calle` VARCHAR(45) NULL,
  `colonia` VARCHAR(45) NULL,
  `cp` VARCHAR(9) NULL,
  `delegacion` VARCHAR(45) NULL,
  `pais` VARCHAR(20) NULL,
  `entidad` VARCHAR(30) NULL,
  `tipo` VARCHAR(2) NULL COMMENT '1- Proveedor\n2- Donatario\n',
  `contacto` VARCHAR(75) NULL,
  `correo_contacto` VARCHAR(45) NULL,
  `estado` INT NULL,
  PRIMARY KEY (`id_proveedor`));


-- -----------------------------------------------------
-- Table `mydb`.`especies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`especies` ;

CREATE TABLE IF NOT EXISTS `mydb`.`especies` (
  `id_especie` INT NOT NULL AUTO_INCREMENT,
  `descripcion` (255) NULL,
  `estado` INT NULL,
  PRIMARY KEY (`id_especie`));


-- -----------------------------------------------------
-- Table `mydb`.`programas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`programas` ;

CREATE TABLE IF NOT EXISTS `mydb`.`programas` (
  `id_programa` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  `estado` INT NULL,
  PRIMARY KEY (`id_programa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`subprogramas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`subprogramas` ;

CREATE TABLE IF NOT EXISTS `mydb`.`subprogramas` (
  `id_subprograma` INT NOT NULL,
  `programas_id_programa` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  `estado` INT NULL,
  PRIMARY KEY (`id_subprograma`),
  INDEX `fk_subprogramas_programas1_idx` (`programas_id_programa` ASC),
  CONSTRAINT `fk_subprogramas_programas1`
    FOREIGN KEY (`programas_id_programa`)
    REFERENCES `mydb`.`programas` (`id_programa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`eventos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`eventos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`eventos` (
  `id_evento` INT NOT NULL AUTO_INCREMENT,
  `subprogramas_idsubprogramas` INT NOT NULL,
  `fecha` DATE NULL,
  `descripcion` VARCHAR(45) NULL,
  `pais` VARCHAR(25) NULL,
  `ciudad` VARCHAR(30) NULL,
  `entidad` INT NULL,
  `estado` INT NULL,
  PRIMARY KEY (`id_evento`),
  INDEX `fk_eventos_subprogramas1_idx` (`subprogramas_idsubprogramas` ASC),
  CONSTRAINT `fk_eventos_subprogramas1`
    FOREIGN KEY (`subprogramas_idsubprogramas`)
    REFERENCES `mydb`.`subprogramas` (`id_subprograma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`apoyos-gastos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`apoyos-gastos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`apoyos-gastos` (
  `id_apoyo` INT NOT NULL AUTO_INCREMENT,
  `apoyo-gasto` CHAR(2) NULL COMMENT '1-Apoyo\n2-Gasto\n',
  `especies_id_especie` INT NOT NULL,
  `anio` INT NOT NULL,
  `folio` (255) NULL COMMENT 'Folio asignado internamente por el usuario\n',
  `tipo` CHAR(2) NULL COMMENT '1-Dinero\n2-Especie\n',
  `cantidad` FLOAT NULL,
  `unidad` VARCHAR(45) NULL COMMENT 'Unidad en la que se cuantificará el apoyo\n',
  `pais` VARCHAR(45) NULL,
  `estado` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  `moneda` CHAR(2) NULL,
  `tipo_cambio` VARCHAR(45) NULL,
  `fcambio` DATE NULL,
  `freferencia` DATE NULL,
  `fcaptura` DATE NULL,
  `observaciones` VARCHAR(255) NULL,
  `frecuencia` INT NULL,
  `eventos_id_evento` INT NOT NULL,
  `estado` INT NULL,
  PRIMARY KEY (`id_apoyo`),
  INDEX `fk_apoyos-gastos_especies1_idx` (`especies_id_especie` ASC),
  INDEX `fk_apoyos-gastos_eventos1_idx` (`eventos_id_evento` ASC),
  CONSTRAINT `fk_apoyos-gastos_especies1`
    FOREIGN KEY (`especies_id_especie`)
    REFERENCES `mydb`.`especies` (`id_especie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_apoyos-gastos_eventos1`
    FOREIGN KEY (`eventos_id_evento`)
    REFERENCES `mydb`.`eventos` (`id_evento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`proovedores_apoyos-gastos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`proovedores_apoyos-gastos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`proovedores_apoyos-gastos` (
  `proovedores_id_donatario` INT NOT NULL,
  `apoyos-gastos_id_apoyo-gasto` INT NOT NULL,
  `tipo_transaccion` VARCHAR(4) NULL COMMENT 'Refiere si es proveedor o donatario\n',
  PRIMARY KEY (`proovedores_id_donatario`, `apoyos-gastos_id_apoyo-gasto`),
  INDEX `fk_proovedores_has_apoyos_apoyos1_idx` (`apoyos-gastos_id_apoyo-gasto` ASC),
  INDEX `fk_proovedores_has_apoyos_proovedores1_idx` (`proovedores_id_donatario` ASC),
  CONSTRAINT `fk_proovedores_has_apoyos_proovedores1`
    FOREIGN KEY (`proovedores_id_donatario`)
    REFERENCES `mydb`.`proovedores` (`id_proveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_proovedores_has_apoyos_apoyos1`
    FOREIGN KEY (`apoyos-gastos_id_apoyo-gasto`)
    REFERENCES `mydb`.`apoyos-gastos` (`id_apoyo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`referencias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`referencias` ;

CREATE TABLE IF NOT EXISTS `mydb`.`referencias` (
  `id_referencia` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`id_referencia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`referencias_apoyos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`referencias_apoyos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`referencias_apoyos` (
  `referencias_id_referencia` INT NOT NULL,
  `apoyos_id_apoyo` INT NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`referencias_id_referencia`, `apoyos_id_apoyo`),
  INDEX `fk_referencias_has_apoyos_apoyos1_idx` (`apoyos_id_apoyo` ASC),
  INDEX `fk_referencias_has_apoyos_referencias1_idx` (`referencias_id_referencia` ASC),
  CONSTRAINT `fk_referencias_has_apoyos_referencias1`
    FOREIGN KEY (`referencias_id_referencia`)
    REFERENCES `mydb`.`referencias` (`id_referencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_referencias_has_apoyos_apoyos1`
    FOREIGN KEY (`apoyos_id_apoyo`)
    REFERENCES `mydb`.`apoyos-gastos` (`id_apoyo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `mydb` ;

-- -----------------------------------------------------
-- Placeholder table for view `mydb`.`view1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`view1` (`id` INT);

-- -----------------------------------------------------
-- Placeholder table for view `mydb`.`view2`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`view2` (`id` INT);

-- -----------------------------------------------------
-- Placeholder table for view `mydb`.`view3`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`view3` (`id` INT);

-- -----------------------------------------------------
-- View `mydb`.`view1`
-- -----------------------------------------------------
DROP VIEW IF EXISTS `mydb`.`view1` ;
DROP TABLE IF EXISTS `mydb`.`view1`;
USE `mydb`;


-- -----------------------------------------------------
-- View `mydb`.`view2`
-- -----------------------------------------------------
DROP VIEW IF EXISTS `mydb`.`view2` ;
DROP TABLE IF EXISTS `mydb`.`view2`;
USE `mydb`;


-- -----------------------------------------------------
-- View `mydb`.`view3`
-- -----------------------------------------------------
DROP VIEW IF EXISTS `mydb`.`view3` ;
DROP TABLE IF EXISTS `mydb`.`view3`;
USE `mydb`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;